export default [
    { name: "None", gradient: "" },
    { name: "Sunrise", gradient: "linear-gradient(to right, #ff9933, #66b3ff)" },
    { name: "Sunset", gradient: "linear-gradient(to right, #ff5e3a, #f0ca4c)" },
    { name: "Ocean Blue", gradient: "linear-gradient(to right, #2193b0, #6dd5ed)" },
    { name: "Lemon Twist", gradient: "linear-gradient(to right, #fbd786, #f7797d)" },
    { name: "Peach", gradient: "linear-gradient(to right, #ffb347, #ffcc33)" },
    { name: "Purple Haze", gradient: "linear-gradient(to right, #8e2de2, #4a00e0)" },
    { name: "Mojito", gradient: "linear-gradient(to right, #1d976c, #93f9b9)" },
    { name: "Sunkist", gradient: "linear-gradient(to right, #f2994a, #f2c94c)" },
    { name: "Cherry Blossom", gradient: "linear-gradient(to right, #ffafbd, #ffc3a0)" },
    { name: "Night Sky", gradient: "linear-gradient(to right, #434343, #000000)" },
    { name: "Fire", gradient: "linear-gradient(to right, #ff512f, #dd2476)" },
    { name: "Forest", gradient: "linear-gradient(to right, #5a3f37, #2c7744)" },
    { name: "Sea", gradient: "linear-gradient(to right, #2b5876, #4e4376)" },
    { name: "Sunburst", gradient: "linear-gradient(to right, #ff6e7f, #bfe9ff)" }]
