export default [
    {
      "color-scheme": "light",
      "primary": "#570df8",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "accent": "#37cdbe",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "synthwave"
    },
    {
      "color-scheme": "light",
      "primary": "#ff79c6",
      "primary-content": "#ffffff",
      "secondary": "#bd93f9",
      "accent": "#ffb86c",
      "neutral": "#44475a",
      "base-100": "#282a36",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "dracula"
    },
    {
      "color-scheme": "light",
      "primary": "#34d399",
      "primary-content": "#ffffff",
      "secondary": "#a78bfa",
      "accent": "#60a5fa",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "emerald"
    },
    {
      "color-scheme": "light",
      "primary": "#570df8",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "accent": "#37cdbe",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "cupcake"
    },
    {
      "color-scheme": "light",
      "primary": "#e879f9",
      "primary-content": "#ffffff",
      "secondary": "#a855f7",
      "accent": "#f472b6",
      "neutral": "#4b5563",
      "base-100": "#ffffff",
      "info": "#38bdf8",
      "success": "#4ade80",
      "warning": "#fbbf24",
      "error": "#fb7185",
      "theme": "pastel"
    },
    {
      "color-scheme": "light",
      "primary": "#3b82f6",
      "primary-content": "#ffffff",
      "secondary": "#1d4ed8",
      "accent": "#60a5fa",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#0ea5e9",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "theme": "aqua"
    },
    {
      "color-scheme": "light",
      "primary": "#f97316",
      "primary-content": "#ffffff",
      "secondary": "#fbbf24",
      "accent": "#a855f7",
      "neutral": "#374151",
      "base-100": "#f3f4f6",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626",
      "theme": "valentine"
    },
    {
      "color-scheme": "light",
      "primary": "#f9a8d4",
      "primary-content": "#ffffff",
      "secondary": "#f472b6",
      "accent": "#fb7185",
      "neutral": "#374151",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#34d399",
      "warning": "#fbbf24",
      "error": "#ef4444",
      "theme": "corporate"
    },
    {
      "color-scheme": "dark",
      "primary": "#000000",
      "primary-content": "#ffffff",
      "secondary": "#ffffff",
      "accent": "#4ade80",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#3b82f6",
      "success": "#22c55e",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "black"
    },
    {
      "color-scheme": "light",
      "primary": "#f59e0b",
      "primary-content": "#ffffff",
      "secondary": "#fbbd23",
      "accent": "#60a5fa",
      "neutral": "#374151",
      "base-100": "#f3f4f6",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626",
      "theme": "bumblebee"
    }
  ];
  